name: Create npm package

on:
  release:
    types: [created]

jobs:
  create_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ma-residence'

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build

      - name: Set package version
        run: sed -i 's/RELEASE_VERSION/'"$RELEASE_VERSION"'/g' dist/package.json

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
